version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: 'npm install'
      - run:
          name: 'Run test case'
          command: 'npm run test'


workflows:
  integration:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
